language: node_js
os: windows
node_js: 10.15
sudo: required
addons:
  ssh_known_hosts: 148.70.216.46
cache:
  directories:
  - node_modules
install:
- npm install
after_success:
- ssh root@148.70.216.46 StrictHostKeyChecking=no 'cd /code/app-code-question && git
  pull'
before_install:
- openssl aes-256-cbc -K $encrypted_13380183eaa9_key -iv $encrypted_13380183eaa9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)